name: plan_api
description: The interface and models for api planner.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  equatable: ^2.0.3
  intl: ^0.19.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
