name: 'simple_day_planner'

version: '1.0.0+1'

publish_to: none

environment: 
  sdk: '^3.4.0'

description: A simple day planner.

dependencies: 
  bloc: '^8.1.3'
  flutter: 
    sdk: flutter
  flutter_bloc: '^8.1.4'
  flutter_localizations: 
    sdk: flutter
  flutter_reorderable_list: ^1.3.1
  intl: '^0.19.0'
  local_storage_plan_api: 
    path: 'packages/local_storage_plan_api'
  meta: ^1.12.0
  plan_api: 
    path: 'packages/plan_api'
  plan_repository: 
    path: 'packages/plan_repository'
  provider: ^6.1.2
  scroll_time_picker: ^1.1.1
  sqflite_common_ffi_web: ^0.4.3+1
  syncfusion_flutter_datepicker: ^26.1.42

dev_dependencies: 
  bloc_test: '^9.1.6'
  flutter_test: 
    sdk: flutter
  mocktail: '^1.0.3'
  pubspec_dependency_sorter: '^1.0.5'
  very_good_analysis: '^5.1.0'

flutter: 
  uses-material-design: true
  generate: true
