name: plan_repository
description: A repository that handles todo related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.3+1
dependencies:
  plan_api:
    path: ../plan_api
    
  path: ^1.9.0
  sqflite: ^2.3.3+1
  intl: ^0.19.0
